name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # This will match all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install project dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Build Docker image
      run: docker build -t vue-blog:latest .

    - name: Save Docker image
      run: docker save vue-blog:latest > image.tar

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Create known_hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts

    - name: Add server to known hosts
      run: ssh-keyscan 60.204.251.220 >> ~/.ssh/known_hosts

    - name: Transfer image to server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} scp image.tar root@60.204.251.220:/tmp

    - name: Load image and restart container on server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh root@60.204.251.220 "docker load < /tmp/image.tar && docker stop vueblog && docker rm vueblog && docker run -d --name vueblog -p 80:80 vue-blog:latest"
